package utils.extras;

public class TransactionTypes {
    public static final int MESSAGE_TYPE_STRING = 1;
    public static final int MESSAGE_TYPE_COURSE = 2;
    public static final int MESSAGE_TYPE_SENDER_WITH_COURSE = 3;
    public static final int MESSAGE_TYPE_RECEIVER_WITH_COURSE = 4;
    public static final int USER_DELETE_MESSAGE = 5;
    public static final int USER_CHAT_CONTENT_ALREADY_EXIST = 1;
    public static final int USER_CHAT_CONTENT_TYPE_SEARCH = 2;
    public static final int USER_SEE_CHAT = 1;
    public static final int USER_SEE_MAIN = 2;
    public static final String TRAINER_SEE_COURSE_UPLOAD = "courseUpload";
    public static final String TRAINER_SEE_COURSE_EDIT = "courseEdit";
    public static final String USER_COME_BACK = "userComeBackMain";
    public static final String LAYOUT_MESSAGE_SEND = "messageSend";
    public static final String LAYOUT_MESSAGE_SHARE = "courseShare";
    public static final String LAYOUT_MESSAGE_NORMAL = "normalMessage";
    public static final int doLogin = 1;
    public static final int doRegister = 2;
    public static final int doGetCourses = 3;
    public static final int doGetLikesCount = 4;
    public static final int doAddCourseLike = 5;
    public static final int isUserCourseLikeControl = 6;
    public static final int doUnlikeCourse = 7;
    public static final int doGetMyLikeCourses = 8;
    public static final int doGetMyChatContent = 9;
    public static final int doGetMyCurrentLastMessage = 10;
    public static final int doGetChatDetail = 11;
    public static final int doSendMessage = 12;
    public static final int doUserDeleteMessage = 13;
    public static final int doUserSearch=14;
    public static final int doUserSendMessageWithCourse=15;
    public static final int doUserClickChatDetailCourse=16;
    public static final int doUserGetProfile =17;
    public static final int doUserChangePassword=18;
    public static final int doTrainerCourseUpload=19;
    public static final int doTrainerGetMyUploads =20;
    public static final int doTrainerUpdateMyCourse=21;
    public static final int doTrainerDeleteMyCourse=21;
    public static final int doSearch=22;
    public static final int doForgotPassword=23;
    public static final int doChangePassword=24;
    public static final int doReSendMailCode=25;
    public static final int doUserSearchCourse=26;
}
